### ISSUE TITLE
method rename proposal

### ISSUE THREAD

**Issue by prepare** [jstedfast/HtmlKit#10]
just  look only method name, and documentation comment (Html5)

this is my proposal
71cf4e75e66ce787fbaea03752c43025255a3208

the code review / study is more easy!

**Comment by jstedfast** [comment]
Why call it R##_?

**Comment by prepare** [comment]
I think ... when review a code, 
one can see that each method match with the 
name of state in Html5 spec
and can look back to the reference :)
