### ISSUE TITLE
Void elements should be reported as empty

### ISSUE THREAD

**Issue by fogzot** [jstedfast/HtmlKit#12]
The HTML syntax (https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#elements-0) defines a number of *void elements* that don't have a close tag. In the XML serialization (`<br />`) they are correctly tokenized, with the attribute `IsEmptyElement` set to true but in the HTML serialization (`<br>`) the same attribute is false.

Is this something that should be managed by the client application or it is a bug in HtmlKit?

**Comment by jstedfast** [comment]
Sorry, didn't see this until now... yes, I think that would be a bug in HtmlKit.

**Comment by jstedfast** [comment]
Actually, hmmm, I'm not sure... I think I may have not marked them as `IsEmptyElement` because the idea was to maintain `<br>` vs `<br/>` when reserializing tag tokens.

You can use `tag.Id.IsEmptyElement()` to check if the tag itself is a void element.

**Comment by jstedfast** [comment]
Maybe I can add a property to `HtmlTagToken` called `IsVoidElement`?

**Comment by fogzot** [comment]
No problem, thank you for your answer.

After working on it and writing an HTML parser that uses HtmlKit as its tokenizer I am convinced that this is not a bug. There are *lots* of rules that define a well formed document and the bare minimum is to keep track of opening/closing tag pairs: in this context HtmlKit does the right thing: it already provides a list of void tags that can be used to check if the current open tag should be closed or not.

We have some special requirement like parsing XML namespaces if present (for custom template tags) but silently ignore them if not present (for special tag and attribute names used by JS libraries like vue.js, e.g., `v:loop=...`) and HtmlKit was **perfect** as a tokenizer. So, thank you very much.

**Comment by fogzot** [comment]
Maybe it wasn't clear, no need to add `IsVoidElement`, at its core the parser just uses code like:

```
if (tag.IsEndTag) {
    HtmlName name = GetName(builder, tokenizer, tag.Name, false);
    if (tag.Id.IsEmptyElement()) {
        throw HtmlParseException.Create("closing tag for void element",
            tokenizer.LineNumber, tokenizer.LinePosition);
    }
    if (name != builder.CurrentElement.Name) {
        throw HtmlParseException.MismatchedTag(builder.CurrentElement, name,
            tokenizer.LineNumber, tokenizer.LinePosition);
    }
    builder.Up();
}
else {
    HtmlName name = GetName(builder, tokenizer, tag);
    builder.Element(name,
        x => x.SetLineInfo(tokenizer.LineNumber, tokenizer.LinePosition));

    foreach (var attribute in tag.Attributes) {
        // Attributes can have a namespace OR be namespace definitions.
        builder.Attribute(GetName(builder, tokenizer, attribute.Name, true), attribute.Value,
            x => x.SetLineInfo(tokenizer.LineNumber, tokenizer.LinePosition));
    }

    if (tag.IsEmptyElement || tag.Id.IsEmptyElement()) {
        builder.Up();
    }
}
```

**Comment by jstedfast** [comment]
Okay, so you've got everything you need?

**Comment by fogzot** [comment]
Yes, everything. Thanks again.

**Comment by fogzot** [comment]
Yes, everything. Thanks again.
