### ISSUE TITLE
Reliability of HtmlTokenizer.LineNumber/LinePosition

### ISSUE THREAD

**Issue by Jither** [jstedfast/HtmlKit#13]
Not really an issue, but...

Stumbled upon this brilliant library while considering writing a tokenizer myself - in order to even semi-reliably being able to locate the position of an element inside the source HTML, without resorting to e.g. regex. Need it for patching of HTML files (e.g. automatically inserting <script> or <link> elements at given positions without touching the surrounding HTML).

Am I right in thinking that LineNumber/LinePosition will be off by 1, iff the last token was an HtmlDataToken (due to lookahead)? Or are there any edge cases I'm missing that you can think of? I can't quite wrap my head around the HTML tokenization spec at the moment.

**Comment by jstedfast** [comment]
Sorry for the delay, I only just now noticed this question.

To answer your question: I think so, yes, because it'll read a `'<'` character and then emit the data token.
