### ISSUE TITLE
HtmlKit manipulates the attribute value when they contain HTML special entities

### ISSUE THREAD

**Issue by mohammadreza-plutoflume** [jstedfast/HtmlKit#17]
**Describe the bug**
HtmlKit manipulates the attribute value when they contain HTML special entities!
We expect when an attribute value is returned it should literarily be equal to the input stream!

**Platform (please complete the following information):**
 - OS: Windows & Linux
 - .NET Framework: `.Net 6.0` & `.NET Framework 4.8`
 - HtmlKit Version: 1.1.0

**To Reproduce**
1. Create a new Console application
1. Add the following HTML file in the project and mark it as `Copy if newer`:
    ```
    <!DOCTYPE html>

    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title></title>
    </head>
    <body>
        <a href="https://google.com/?q=val-&laquo;-val" name="val-&laquo;">The First Link</a>
        <br />
        <a href="https://google.com/?q=val-&amp;-val" name="val-&amp;">The Second Link</a>
    </body>
    </html>
    ```
1. Copy-Paste the following code in `Program.cs` file:
    ```
    using HtmlKit;

    namespace HtmlKitTestProject
    {
        internal class Program
        {
            static void Main(string[] args)
            {
                using var stream = new FileStream("index.html", FileMode.Open, FileAccess.Read);
                using var reader = new StreamReader(stream);

                var tokenizer = new HtmlTokenizer(reader);
                HtmlToken token;

                while (tokenizer.ReadNextToken(out token))
                {
                    switch (token.Kind)
                    {
                        case HtmlTokenKind.Tag:
                            var tag = (HtmlTagToken)token;

                            if (tag.Id != HtmlTagId.A)
                                continue;

                            foreach (var attribute in tag.Attributes)
                            {
                                if (attribute.Value != null)
                                    Console.WriteLine(" {0}={1}", attribute.Name, $"{attribute.Value}");
                                else
                                    Console.WriteLine(" {0}", attribute.Name);
                            }
                            break;
                    }
                }

                Console.ReadLine();
            }
        }
    }
    ```
1. Run the project and check the output:
    ![image](https://github.com/jstedfast/HtmlKit/assets/97455666/1a3e5879-16b0-4d10-a5f0-e6dc9645f653)

**Expected behavior**
The HTML file contains attributes with some HTML special entities as their values:
![image](https://github.com/jstedfast/HtmlKit/assets/97455666/84283d73-68ac-412f-89bb-66038f9dca03)
When an attribute value is returned it should literarily be equal to the input stream but, as you see it's converted to their decoded version!
![image](https://github.com/jstedfast/HtmlKit/assets/97455666/fde35dee-658d-42c1-958d-115e50772227)

**Comment by jstedfast** [comment]
I don't understand why this is a bug?
