### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by prepare** [jstedfast/HtmlKit#2]
Hello

I don't intend to fragment you library. 

I  just want to use it with the HtmlRenderer (https://github.com/prepare/HTML-Renderer).
so I must change something to fit with the HtmlRenderer.

I'm a young developer, feel free to suggest/comment 
Thank you for your work :)

**Comment by jstedfast** [comment]
I did not expect anyone to discover HtmlKit so quickly.

Feel free to use it for whatever you'd like.
