### ISSUE TITLE
<xmp> tags are parsed with HtmlTagId.Unknown

### ISSUE THREAD

**Issue by firat-plutoflume** [jstedfast/HtmlKit#38]
**Describe the bug**

Hello,

I was trying to parse some files with `<xmp>` tags in them and noticed when I use the `HtmlTokenizer` it extracts an HtmlTagToken with `HtmlTagId.Unknown`. I see in the HtmlTagId enum there is a value for xmp tags, is this intentional and if so, could you tell me if there are any other tags that have the same behaviour please?

Thanks in advance

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.] Linux
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.] .net8
 - HtmlKit Version: 1.1.0

**To Reproduce**

you can use this simple example below:
```
<xmp>test</xmp>
```

here is what I see in the debugger:
![image](https://github.com/user-attachments/assets/3c586af8-53ba-4227-abe0-9f45498de792)

**Expected behavior**

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
// Add your code snippet here.
```

**Additional context**

**Comment by jstedfast** [comment]
Looks like a bug.

**Comment by jstedfast** [comment]
I can't reproduce the bug *shrug*

**Comment by jstedfast** [comment]
Looks like I have some changes that were never pushed in a release. Can you try the latest HtmlKit source code and see if it fixes things for you? If so, I'll try to make a new release.

**Comment by firat-plutoflume** [comment]
yes, it works on the latest version, thanks!

I've noticed that MimeKit.Text.HtmlTokenizer also works correctly, we are currently using both libraries, so can we maybe use MimeKit.Text instead of having HtmlKit as a separate dependency? I believe that would be more 'up-to-date' compared to HtmlKit, is that right or are there any differences between?

**Comment by jstedfast** [comment]
Yes, MimeKit more-or-less imports *all* of HtmlKit into the MimeKit.Text namespace.

I had originally implemented it for MimeKit and then later thought maybe it would have some usefulness outside of MimeKit so I made HtmlKit.

**Comment by firat-plutoflume** [comment]
yes it has definitely uses as a separate library, but in our case I think it's easier/cleaner to just use MimeKit alone. thanks for quick response and help 👍

**Comment by jstedfast** [comment]
I just released v1.2.0, so this should work now even if you still used HtmlKit instead of MimeKit.
